export const FEELING_SELECTED_ACTION = 'FEELING_SELECTED_ACTION';
export const FEELING_SUCCESS_ACTION = 'FEELING_SUCCESS_ACTION';
export const FEELING_FAILURE_ACTION = 'FEELING_FAILURE_ACTION';
export const SEND_HEALTH_STAT_ACTION = 'SEND_HEALTH_STAT_ACTION';
export const STORE_STAT_ID_ACTION = 'STORE_STAT_ID_ACTION';
export const STAT_ID_SKIPPED_ACTION = 'STAT_ID_SKIPPED_ACTION';
