export const EDIT_OTP_ACTION = 'EDIT_OTP_ACTION';
export const OTP_SUCCESS_ACTION = 'OTP_SUCCESS_ACTION';
export const SEND_OTP_ACTION = 'SEND_OTP_ACTION';
export const OTP_FAILURE_ACTION = 'OTP_FAILURE_ACTION';
export const RESEND_OTP_ACTION = 'RESEND_OTP_ACTION';
export const RESEND_OTP_FAILURE_ACTION = 'RESEND_OTP_FAILURE_ACTION';
export const RESEND_OTP_SUCCESS_ACTION = 'RESEND_OTP_SUCCESS_ACTION';
export const RESET_OTP_TO_INITIAL_STATE = 'RESET_OTP_TO_INITIAL_STATE';
