export const UPDATE_PASSWORD_ACTION = 'UPDATE_PASSWORD_ACTION';
export const UPDATE_PASSWORD_SUCCESS_ACTION = 'UPDATE_PASSWORD_SUCCESS_ACTION';
export const UPDATE_PASSWORD_FAILURE_ACTION = 'UPDATE_PASSWORD_FAILURE_ACTION';
