export const GET_SHARE_HISTORY_ACTION = 'GET_SHARE_HISTORY_ACTION';
export const SHARE_HISTORY_SUCCESS_ACTION = 'SHARE_HISTORY_SUCCESS_ACTION';
export const SHARE_HISTORY_FAILURE_ACTION = 'SHARE_HISTORY_FAILURE_ACTION';
