import {StyleSheet, Platform} from 'react-native';
import {Layout} from '../../../../utilities';

const {HEX_COLOR_CODES, LAYOUT_CONSTRAINTS, FONTS} = Layout;

export const Style = StyleSheet.create({
  countryPickerContainer: {
    width: 'auto',
    justifyContent: 'center',
    backgroundColor: HEX_COLOR_CODES.WALKTHROUGH_BG,
    bottom: 0,
  },
  modal: {
    flex: 1,
    backgroundColor: HEX_COLOR_CODES.WALKTHROUGH_BG,
  },
  meContainer: {
    width: LAYOUT_CONSTRAINTS.SCREEN_WIDTH,
    height: LAYOUT_CONSTRAINTS.SCREEN_HEIGHT,
    backgroundColor: HEX_COLOR_CODES.DARKGRAY,
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: HEX_COLOR_CODES.WALKTHROUGH_BG,
    flex: 1,
    alignItems: 'center',
  },
  addImageButton: {
    position: 'absolute',
    top: -56,
    bottom: 0,
    backgroundColor: HEX_COLOR_CODES.MID_GRAY,
    height: 36,
    width: 36,
    borderRadius: 18,
  },
  userImage: {
    height: '100%',
    width: '100%',
    borderRadius: 77,
  },
  trackColorWhenFalse: {
    color: HEX_COLOR_CODES.GREEN,
  },
  trackColorWhenTrue: {
    color: HEX_COLOR_CODES.GREEN,
  },
  imgBlurredQR: {
    width: 200,
    height: 200,
  },
  infoAlertcontainer: {
    shadowColor: HEX_COLOR_CODES.WHITE,
    shadowOffset: {
      width: 0,
      height: -2,
    },
    shadowOpacity: 0.43,
    shadowRadius: 9.51,
    elevation: 15,
    height: 148,
    marginTop: 120,
    width: LAYOUT_CONSTRAINTS.WINDOW_WIDTH - 28,
    backgroundColor: HEX_COLOR_CODES.WHITE,
    borderRadius: 4,
  },
  triangle: {
    position: 'absolute',
    width: 0,
    height: 0,
    alignSelf: 'center',
    top: -15,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 19,
    borderRightWidth: 19,
    borderBottomWidth: 19,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: HEX_COLOR_CODES.DARKGRAY,
  },
  bottomTriangle: {
    position: 'absolute',
    width: 0,
    height: 0,
    alignSelf: 'center',
    bottom: -15,
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 19,
    borderRightWidth: 19,
    borderBottomWidth: 19,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: HEX_COLOR_CODES.DARKGRAY,
    transform: [{rotate: '180deg'}],
  },
  infoAlertSubcontainer: {
    height: '100%',
    width: '100%',
    borderRadius: 4,
    backgroundColor: HEX_COLOR_CODES.DARKGRAY,
  },
  infoLabel: {
    fontSize: 14,
    fontFamily: FONTS.SOFIA_REGULAR,
    color: HEX_COLOR_CODES.WHITE,
    paddingLeft: 18,
    paddingTop: 32,
    marginRight: 18,
  },
  infoLabelColor: {
    color: HEX_COLOR_CODES.WHITE,
  },

  profileInfoIconContainer: {
    position: 'absolute',
    right: 3,
    top: 12,
    height: 35,
    width: 37,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  crossIconContainer: {
    position: 'absolute',
    right: 3,
    top: 4,
    height: 35,
    width: 37,
    borderRadius: 4,
    backgroundColor: '#0000',
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileInfoButton: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
  },
  profileInfoIcon: {
    position: 'relative',
    right: 12,
    height: 24,
    width: 24,
  },
  unverifiedProfileInfoIconBackGround: {
    backgroundColor: HEX_COLOR_CODES.ORANGE,
  },
  infoIconTextStyle: {
    height: 0,
    width: 0,
  },
  nextButtonContainer: {
    position: 'absolute',
    bottom: 0,
    right: 0,
    left: 0,
    height: 50,
    flexDirection: 'row',
    alignItems: 'center',
  },
  nextButton: {
    position: 'absolute',
    bottom: 16,
    right: 18,
    width: 101,
    height: 48,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: HEX_COLOR_CODES.GREEN_BLUE,
  },
  nextButtonLabel: {
    paddingTop: Platform.OS === 'ios' ? 8 : 0,
    fontSize: 17,
    color: HEX_COLOR_CODES.WHITE,
    fontFamily: FONTS.SOFIA_REGULAR,
  },
  skipButton: {
    position: 'absolute',
    color: HEX_COLOR_CODES.WHITE,
    fontFamily: FONTS.SOFIA_REGULAR,
    left: 18,
    width: 101,
    height: 48,
    fontSize: 17,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
    textDecorationLine: 'underline',
  },
  rotadedMark: {
    position: 'absolute',
    backgroundColor: HEX_COLOR_CODES.BLACK,
    height: 19,
    width: 19,
    zIndex: 5,
    elevation: 5,
    borderRadius: 4,
    transform: [{rotate: '45deg'}],
  },
  highlightedStep: {
    top: 100,
    height: 200,
    width: 200,
  },
  shareIdButtonContainer: {
    position: 'absolute',
    bottom: -74,
    alignItems: 'center',
    width: '100%',
  },
  shareIdButton: {
    bottom: 0,
    alignItems: 'center',
    backgroundColor: HEX_COLOR_CODES.BLACK,
    height: 52,
  },
  shareMyIdIcon: {
    position: 'relative',
    marginLeft: 24,
    height: 20,
    width: 22,
    bottom: 2,
  },
  buttonCustomStyle: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  shareIdButtonTitle: {
    color: HEX_COLOR_CODES.WHITE,
    fontSize: 17,
    marginLeft: 8,
  },
  scanMeButton: {
    backgroundColor: HEX_COLOR_CODES.WHITE,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
    position: 'absolute',
    top: -96,
    height: 68,
    width: 80,
    right: 16,
  },
  scanMeIcon: {
    height: 20,
    width: 12,
  },
  scanMeText: {
    fontFamily: FONTS.SOFIA_REGULAR,
    color: HEX_COLOR_CODES.GREEN,
    marginTop: 8,
  },
  switchStyle: {position: 'absolute', top: -55},
  tutorial6Container: {height: 'auto'},
});
