export const LOGOUT_ACTION = 'LOGOUT_ACTION';
export const LOGOUT_SUCCESS_ACTION = 'LOGOUT_SUCCESS_ACTION';
export const LOGOUT_FAILURE_ACTION = 'LOGOUT_FAILURE_ACTION';
export const RESET_STORE_TO_INITIAL_STATE_ACTION =
  'RESET_STORE_TO_INITIAL_STATE_ACTION';
export const DELETE_ACCOUNT_ACTION = 'DELETE_ACCOUNT_ACTION';
