export const EDIT_EMAIL_FOR_FORGOTTEN_PASSWORD_ACTION =
  'EDIT_EMAIL_FOR_FORGOTTEN_PASSWORD_ACTION';
export const FORGOTTEN_PASSWORD_ACTION = 'FORGOTTEN_PASSWORD_ACTION';
export const FORGOTTEN_PASSWORD_SUCCESS_ACTION =
  'FORGOTTEN_PASSWORD_SUCCESS_ACTION';
export const FORGOTTEN_PASSWORD_FAILURE_ACTION =
  'FORGOTTEN_PASSWORD_FAILURE_ACTION';
