export const GET_NOTIFICATIONS_ACTION = 'GET_NOTIFICATIONS_ACTION';
export const NOTIFICATIONS_SUCCESS_ACTION = 'NOTIFICATIONS_SUCCESS_ACTION';
export const NOTIFICATIONS_FAILURE_ACTION = 'NOTIFICATIONS_FAILURE_ACTION';
export const DELETE_NOTIFICATIONS_ACTION = 'DELETE_NOTIFICATIONS_ACTION';
export const DELETE_NOTIFICATIONS_SUCCESS_ACTION =
  'DELETE_NOTIFICATIONS_SUCCESS_ACTION';
export const DELETE_NOTIFICATIONS_FAILURE_ACTION =
  'DELETE_NOTIFICATIONS_FAILURE_ACTION';
export const CHANGE_NOTIFICATION_STATUS_ACTION =
  'CHANGE_NOTIFICATION_STATUS_ACTION';
