export const GET_USER_PROFILE_ACTION = 'GET_USER_PROFILE_ACTION';
export const EDIT_USER_PROFILE_ACTION = 'EDIT_USER_PROFILE_ACTION';
export const SHOW_TEST_INFO_ACTION = 'SHOW_TEST_INFO_ACTION';
export const SHOW_TEMPERATURE_INFO_ACTION = 'SHOW_TEMPERATURE_INFO_ACTION';
export const UPDATE_TEMPERATURE_INFO_ACTION = 'UPDATE_TEMPERATURE_INFO_ACTION';
export const UPDATE_MODAL_INDEX_ACTION = 'UPDATE_MODAL_INDEX_ACTION';
export const UPDATE_TEMPERATURE_INFO_SUCESS_ACTION =
  'UPDATE_TEMPERATURE_INFO_SUCESS_ACTION';
export const UPDATE_TEMPERATURE_INFO_FAILURE_ACTION =
  'UPDATE_TEMPERATURE_INFO_FAILURE_ACTION';
export const SHARE_MY_ID_ACTION = 'SHARE_MY_ID_ACTION';
export const GET_USER_PROFILE_SUCCESS_ACTION =
  'GET_USER_PROFILE_SUCCESS_ACTION';
export const GET_USER_PROFILE_FAILURE_ACTION =
  'GET_USER_PROFILE_FAILURE_ACTION';
export const SHOW_TEMP_SUCCESS_ACTION = 'SHOW_TEMP_SUCCESS_ACTION';
export const SHOW_TEMP_FAILURE_ACTION = 'SHOW_TEMP_FAILURE_ACTION';
export const SHOW_HEALTH_INFO_SUCCESS_ACTION =
  'SHOW_HEALTH_INFO_SUCCESS_ACTION';
export const SHOW_HEALTH_INFO_FAILURE_ACTION =
  'SHOW_HEALTH_INFO_FAILURE_ACTION';
export const PROFILE_VISTED_BEFORE_ACTION = 'PROFILE_VISTED_BEFORE_ACTION';
export const DEEP_LINK_GENERATE_ACTION = 'DEEP_LINK_GENERATE_ACTION';
export const SHAR_LINK_ACTION = 'SHAR_LINK_ACTION';
export const SHAR_LINK_ACTION_SUCCESS_ACTION =
  'SHAR_LINK_ACTION_SUCCESS_ACTION';
export const SHAR_LINK_FAILURE_ACTION = 'SHAR_LINK_FAILURE_ACTION';
export const SHOW_USER_BY_ME_SIGN_ACTION = 'SHOW_USER_BY_ME_SIGN_ACTION';
export const CHECK_HEALTH_TEST_MISSING_FIELDS_ACTION =
  'CHECK_HEALTH_TEST_MISSING_FIELDS_ACTION';
export const RESET_HEALTH_TEST_DATA_ACTION = 'RESET_HEALTH_TEST_DATA_ACTION';
export const ADD_HEALTH_TEST_DATA_ACTION = 'ADD_HEALTH_TEST_DATA_ACTION';
export const EDIT_HEALTH_TEST_DATA_ACTION = 'EDIT_HEALTH_TEST_DATA_ACTION';
export const ADD_HEALTH_TEST_DATA_FAILURE_ACTION =
  'ADD_HEALTH_TEST_DATA_FAILURE_ACTION';
export const ADD_HEALTH_TEST_DATA_SUCCESS_ACTION =
  'ADD_HEALTH_TEST_DATA_SUCCESS_ACTION';
export const LOADER_ACTION = 'LOADER_ACTION';
export const UPDATE_HEALTH_TEST_FIELD_TYPE_AND_INDEX_ACTION =
  'UPDATE_HEALTH_TEST_FIELD_TYPE_AND_INDEX_ACTION';
export const UPLOAD_USER_IMAGE_ACTION = 'UPLOAD_USER_IMAGE_ACTION';
export const UPLOAD_HEALTH_TEST_ACTION = 'UPLOAD_HEALTH_TEST_ACTION';
export const UPLOAD_USER_IMAGE_FAILURE_ACTION =
  'UPLOAD_USER_IMAGE_FAILURE_ACTION';
export const UPDATE_OPENED_INITIAL_DYNAMIC_LINK =
  'UPDATE_OPENED_INITIAL_DYNAMIC_LINK';
export const VISITING_PROFILE_SCREEN_VIA_ACTION =
  'VISITING_PROFILE_SCREEN_VIA_ACTION';
export const BUSINESS_REQUEST_API_ACTION = 'BUSINESS_REQUEST_API_ACTION';
export const BUSINESS_REQUEST_API_SUCCESS_ACTION =
  'BUSINESS_REQUEST_API_SUCCESS_ACTION';
export const BUSINESS_REQUEST_API_FAILURE_ACTION =
  'BUSINESS_REQUEST_API_FAILURE_ACTION';

export const GET_COMPANY_DETAILS = 'GET_COMPANY_DETAILS_ACTION';
export const ACCEPT_SHARE_CONTACT_DETAILS = 'ACCEPT_SHARE_CONTACT_DETAILS';

export const ME_ACCESS_ASK_SHOW = 'ME_ACCESS_ASK_SHOW';
export const ME_ACCESS_ASK_UPDATE_NAME = 'ME_ACCESS_ASK_UPDATE_NAME';
export const ME_ACCESS_ASK_HIDE = 'ME_ACCESS_ASK_HIDE';
export const SHOW_VACCINE_POPUP_ON_HOME_ACTION =
  'SHOW_VACCINE_POPUP_ON_HOME_ACTION';
export const UPDATE_MODAL_PERMISION_INDEX_ACTION =
  'UPDATE_MODAL_PERMISION_INDEX_ACTION';
export const TOGGLE_VACCINE_ACTION = 'TOGGLE_VACCINE_ACTION';
export const TOGGLE_VACCINE_SUCCESS_ACTION = 'TOGGLE_VACCINE_SUCCESS_ACTION';
export const TOGGLE_VACCINE_FAILURE_ACTION = 'TOGGLE_VACCINE_FAILURE_ACTION';
export const SHOW_HEALTH_TEST_IMAGE_LOADER_ACTION =
  'SHOW_HEALTH_TEST_IMAGE_LOADER_ACTION';
export const UPDATE_VERIFY_MODAL_INDEX_ACTION =
  'UPDATE_VERIFY_MODAL_INDEX_ACTION';
export const GENERATE_ME_SIGN_ACTION = 'GENERATE_ME_SIGN_ACTION';
