const testIds = {
  EmailSignIn: 'Email@1',
  PasswordSignIn: 'Password@1',
  SignIn: 'Continue@1',
  ContinueToNextBenefit: 'ContinueToNextBenefit',
  GotoSignInFromBenefits: 'GotoSignInFromBenefits',
  PasswordForgotten: 'PasswordForgotten',
  ContinueToBenefits: 'ContinueToBenefits',
  FirstTut: 'FirstTut',
  skipTutID: 'skipTutID',
  addTestBtn: 'addTestBtn',
  addTemperatureButton: 'addTemperatureButton',
  skipFeeling: 'skipFeeling',
  continueTemperatureAdd: 'continueTemperatureAdd',
  temperatureSwitch: 'temperatureSwitch',
  profileScroll: 'profileScroll',
  Title: 'Title',
  TitlePicker: 'TitlePicker',
  FirstName: 'FirstName',
  LastName: 'LastName',
  MiddleName: 'MiddleName',
  ContinueToContactDetails: 'ContinueToContactDetails',
  ForgottenPasswordEmailField: 'ForgottenPasswordEmailField',
  SendLinkToEmailToResetPassword: 'SendLinkToEmailToResetPassword',
  ContEmail: 'ContEmail',
  ContPassword: 'ContPassword',
  Phone: 'Phone',
  CheckBox: 'CheckBox',
  Eye: 'Eye',
  Logout: 'Log out',
  SettingsTab: 'Settings, tab, 3 of 3',
  Continue: 'Continue',
  Skip: 'Skip',
  OtpTextInput: 'textInput',
  ResendOtp: 'ResendOtp',
  FeelingOne: 'FeelingOne',
  FeelingTwo: 'FeelingTwo',
  FeelingThree: 'FeelingThree',
  FeelingFour: 'FeelingFour',
  SelectFeh: 'SelectFeh',
  SelectCel: 'SelectCel',
  PasswordSettings: 'Password Settings',
  oldPassword: 'oldPassword',
  newPassword: 'newPassword',
  confirmPassword: 'confirmPassword',
  updatePasswordBtn: 'updatePasswordBtn',
  shareIDBtn: 'shareIDBtn',
  shareMeBtn: 'shareMeBtn',
  QRCode: 'QRCode',
  AddAnotherTest: 'AddAnotherTest',
  DeleteTest: 'DeleteTest',
  Centre: 'Centre',
  Type: 'Type',
  TestDate: 'TestDate',
  TestResult: 'TestResult',
  How: 'How',
  ImagePicker: 'ImagePicker',
  temperaturePickerInt: 'temperaturePickerInt',
  tempPickerDec: 'tempPickerDec',
  profileTab: 'Profile, tab, 1 of 3',
  notificationTab: 'Notifications, tab, 2 of 3',
  settingsTab: 'Settings, tab, 3 of 3',
  temperatureResults: 'Temperature Results',
  addNew: 'Add new',
  shareHistory: 'Share history',
  HealthTestsResults: 'Health tests results',
  Edit: 'Edit',
  RemoteWorkToggle: 'Remote Work Toggle',
  workingRemotely: 'Remote work status',
  PersonalAndContactDetails: 'Personal & Contact details',
  updateContactDetails: 'Update Contact Details',
  AppVersion: 'About this app version',
  Invite: 'Invite your friends',
  InviteVia: 'Invite via',
  Done: 'Done',
  btnJumioFailedTryAgain: 'btnJumioFailedTryAgain',
  myCompany: 'My company',
  closeHRPopUp: 'closeHRPopUp',
  addVaccine: 'addVaccine',
  vaccineSwitch: 'vaccineSwitch',
  appBuild: 'appBuild',
  loader: 'loader',
};
module.exports = testIds;
