export const UPDATE_CONTACT_DETAILS_ACTION = 'UPDATE_CONTACT_DETAILS_ACTION';
export const UPDATE_CONTACT_DETAILS_SUCCESS_ACTION =
  'UPDATE_CONTACT_DETAILS_SUCCESS_ACTION';
export const UPDATE_CONTACT_DETAILS_FAILURE_ACTION =
  'UPDATE_CONTACT_DETAILS_FAILURE_ACTION';
export const SET_PERSONAL_DETAILS = 'SET_PERSONAL_DETAILS';
export const GET_CONTACT_DETAILS = 'GET_CONTACT_DETAILS';
export const GET_CONTACT_DETAILS_SUCCESS = 'GET_CONTACT_DETAILS_SUCCESS';
export const GET_CONTACT_DETAILS_FAILURE = 'GET_CONTACT_DETAILS_FAILURE';
