export const APPROVE_HEALTH_TEST_ACTION = 'APPROVE_HEALTH_TEST_ACTION';
export const APPROVE_HEALTH_TEST_SUCCESS_ACTION =
  'APPROVE_HEALTH_TEST_SUCCESS_ACTION';
export const APPROVE_HEALTH_TEST_FAILURE_ACTION =
  'APPROVE_HEALTH_TEST_FAILURE_ACTION';
