export const GET_ALL_COMPANIES = 'GET_ALL_COMPANIES';
export const GET_ALL_COMPANIES_SUCCESS = 'GET_ALL_COMPANIES_SUCCESS';
export const GET_ALL_COMPANIES_FAILURE = 'GET_ALL_COMPANIES_FAILURE';
export const SHOW_COMPANY_IN_PROFILE = 'SHOW_COMPANY_IN_PROFILE';
export const SHOW_COMPANY_IN_PROFILE_FAILURE =
  'SHOW_COMPANY_IN_PROFILE_FAILURE';
export const SET_REMOTE_WORKING = 'SET_REMOTE_WORKING';
export const SET_REMOTE_WORKING_FAILURE = 'SET_REMOTE_WORKING_FAILURE';
export const REMOVE_COMPANY = 'REMOVE_COMPANY';
export const REMOVE_COMPANY_FAILURE = 'REMOVE_COMPANY_FAILURE';
export const UPDATE_COMPANY_DATA = 'UPDATE_COMPANY_DATA';
export const GET_REMOTE_REASONS = 'GET_REMOTE_REASONS';
export const GET_REMOTE_REASONS_SUCCESS = 'GET_REMOTE_REASONS_SUCCESS';
export const GET_REMOTE_REASONS_FAILURE = 'GET_REMOTE_REASONS_FAILURE';
