const types = {
  GET_JUMIO_CREDENTIALS_REQUESTED: 'GET_JUMIO_CREDENTIALS_REQUESTED',
  GET_JUMIO_CREDENTIALS_SUCCEEDED: 'GET_JUMIO_CREDENTIALS_SUCCEEDED',
  GET_JUMIO_CREDENTIALS_FAILED: 'GET_JUMIO_CREDENTIALS_FAILED',
};

export default types;
