export const SELECT_TEMP_TYPE_ACTION = 'SELECT_TEMP_TYPE_ACTION';
export const SELECT_TEMP_INT_ACTION = 'SELECT_TEMP_INT_ACTION';
export const SELECT_TEMP_DEC_ACTION = 'SELECT_TEMP_DEC_ACTION';
export const SEND_TEMP_ACTION = 'SEND_TEMP_ACTION';
export const SEND_TEMP_SUCCESS_ACTION = 'SEND_TEMP_SUCCESS_ACTION';
export const SEND_TEMP_FAILURE_ACTION = 'SEND_TEMP_FAILURE_ACTION';
export const TEMP_SKIPPED_ACTION = 'TEMP_SKIPPED_ACTION';
