import {StyleSheet} from 'react-native';
import {Layout} from '../../../utilities';

const {HEX_COLOR_CODES, LAYOUT_CONSTRAINTS, FONTS} = Layout;

export const Style = StyleSheet.create({
  container: {
    backgroundColor: HEX_COLOR_CODES.WHITE,
    flex: 1,
  },
  scrollViewContainer: {
    flex: 1,
  },
  scrollContentContainer: {
    paddingBottom: 40,
  },
  scanMe: {
    position: 'absolute',
    top: 64,
    height: 68,
    width: 80,
    right: 16,
  },
  scanMeButton: {
    width: '100%',
    height: '100%',
    backgroundColor: HEX_COLOR_CODES.WHITE,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  scrollViewParentContainer: {
    backgroundColor: HEX_COLOR_CODES.WHITE,
    flex: 1,
    bottom: 56,
  },
  loaderView: {
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
  },
  userProfileView: {
    backgroundColor: HEX_COLOR_CODES.LIGHT_GRAY,
    width: '100%',
    height: 392,
  },
  userProfileViewHeightWhenCheckedIn: {
    height: 484,
  },
  adjustedHeight: {
    height: 450,
  },
  dataContainer: {
    flex: 1,
    backgroundColor: HEX_COLOR_CODES.WHITE,
  },
  data: {
    height: 'auto',
    flexDirection: 'row',
  },
  shareButton: {
    width: '100%',
  },
  shareIdButtonContainer: {
    position: 'absolute',
    bottom: 4,
    alignItems: 'center',
    width: '100%',
    minHeight: 60,
  },
  shareMenu: {
    bottom: 80,
    right: 14,
    position: 'absolute',
    width: 179,
    height: 125,
    backgroundColor: HEX_COLOR_CODES.WHITE,
    borderRadius: 4,
    shadowColor: HEX_COLOR_CODES.BLACK,
    shadowOffset: {
      width: 0,
      height: 6,
    },
    shadowOpacity: 0.37,
    shadowRadius: 7.49,
    elevation: 12,
  },
  shareMEMenuButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 20,
    marginTop: 17,
    position: 'relative',
    alignSelf: 'center',
  },
  shareMenuIcon: {
    width: 24,
    height: 26,
    position: 'absolute',
    left: 0,
  },
  shareMeMenuButtonText: {
    color: 'black',
    fontSize: 16,
    position: 'absolute',
    left: 40,
    paddingTop: 4,
  },
  shareOtherMenuButtonText: {
    color: HEX_COLOR_CODES.BLACK,
    fontSize: 16,
    position: 'absolute',
    left: 40,
  },
  shareOtherOptionsButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingLeft: 20,
    position: 'relative',
  },
  shareMEIcon: {
    width: 50,
    height: 50,
  },
  shareIdButton: {
    bottom: 0,
    alignItems: 'center',
    height: 52,
  },
  shareIdButtonBGColorWhenNotDisabled: {
    backgroundColor: HEX_COLOR_CODES.BLACK,
    width: LAYOUT_CONSTRAINTS.SCREEN_WIDTH - 26,
  },
  disabledShareIdButton: {
    backgroundColor: HEX_COLOR_CODES.GRAY,
    width: LAYOUT_CONSTRAINTS.SCREEN_WIDTH - 26,
  },
  buttonCustomStyle: {
    alignItems: 'center',
    flexDirection: 'row',
  },
  shareIdButtonTitle: {
    color: HEX_COLOR_CODES.WHITE,
    fontSize: 17,
    marginLeft: 8,
  },
  userImageContainer: {
    alignSelf: 'center',
    marginTop: 127,
    height: 144,
    width: 144,
    borderRadius: 77,
    backgroundColor: HEX_COLOR_CODES.WHITE,
  },
  uploadImageSign: {},
  scanMeIcon: {
    height: 20,
    width: 12,
  },
  userImage: {
    height: '100%',
    width: '100%',
    borderRadius: 77,
  },
  profileImageButton: {flex: 1},
  profileImageBottomIcon: {
    position: 'absolute',
    right: 8,
    bottom: 0,
    height: 36,
    width: 36,
    borderRadius: 18,
  },
  placeholderImageContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  userName: {
    marginTop: 24,
    alignSelf: 'center',
    fontSize: 24,
    fontFamily: FONTS.SOFIA_REGULAR,
    fontWeight: '600',
    marginHorizontal: 15,
  },
  scanMeText: {
    fontFamily: FONTS.SOFIA_REGULAR,
    color: HEX_COLOR_CODES.GREEN,
    marginTop: 8,
  },
  location: {
    marginTop: 8,
    alignSelf: 'center',
    fontSize: 16,
    fontFamily: FONTS.SOFIA_REGULAR,
    color: HEX_COLOR_CODES.GRAY,
  },
  company: {
    marginTop: 12,
    alignSelf: 'center',
    textAlign: 'center',
    fontSize: 16,
    fontFamily: FONTS.FUTURA,
    color: HEX_COLOR_CODES.DARKGRAY,
    backgroundColor: HEX_COLOR_CODES.WHITE,
    paddingHorizontal: 15,
    paddingTop: LAYOUT_CONSTRAINTS.SCREEN_HEIGHT * 0.013,
    height: 42,
    shadowColor: HEX_COLOR_CODES.BLACK,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  checkedIn: {
    marginLeft: 8,
    fontSize: 16,
    height: 24,
    alignSelf: 'center',
    fontFamily: FONTS.FUTURA,
    color: HEX_COLOR_CODES.WHITE_2,
  },
  checkedInImage: {
    alignSelf: 'center',
    width: 20,
    height: 20,
  },
  checkedInView: {
    elevation: 5,
    marginTop: 12,
    height: 42,
    maxWidth: 220,
    alignSelf: 'center',
    backgroundColor: HEX_COLOR_CODES.ORANGE,
    flexDirection: 'row',
    justifyContent: 'center',
    paddingHorizontal: 15,
  },
  statusButtonContainer: {
    marginTop: 20,
    alignSelf: 'center',
    justifyContent: 'center',
    width: 104,
    height: 35,
    borderWidth: 2,
    backgroundColor: HEX_COLOR_CODES.WHITE,
  },
  statusUnverifiedButtonContainerBorder: {
    borderColor: HEX_COLOR_CODES.ORANGE,
  },
  statusVerifiedButtonContainerBorder: {
    borderColor: HEX_COLOR_CODES.LIGHT_GRAY,
  },
  statusButton: {
    alignSelf: 'center',
  },
  statusLabel: {
    alignSelf: 'center',
    fontFamily: FONTS.SOFIA_REGULAR,
    fontSize: 16,
    paddingTop: 1,
  },
  statusUnverifiedLabel: {
    color: HEX_COLOR_CODES.ORANGE,
  },
  statusVerifiedLabel: {
    color: HEX_COLOR_CODES.GREEN,
  },
  infoIcon: {
    height: 24,
    width: 24,
    marginLeft: 13,
    marginTop: 14,
    backgroundColor: HEX_COLOR_CODES.MID_GRAY,
    borderRadius: 12,
  },
  verifiedIcon: {
    height: 8,
    width: 12,
  },
  infoIconContainer: {
    width: 68,
  },
  verifiedIconCotainer: {
    height: 24,
    width: 24,
    marginLeft: 13,
    marginTop: 14,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: HEX_COLOR_CODES.GREEN,
    borderRadius: 12,
  },
  healthTestLabel: {
    fontSize: 18,
    marginTop: 16,
    fontFamily: FONTS.SOFIA_REGULAR,
  },
  dateLabel: {
    fontSize: 18,
    marginTop: 4,
    fontFamily: FONTS.SOFIA_REGULAR,
    color: HEX_COLOR_CODES.GRAY,
  },
  healthTestStatusLabel: {
    fontSize: 16,
    marginTop: 4,
    fontFamily: FONTS.SOFIA_REGULAR,
  },
  healthTestDetailsContainer: {
    height: 'auto',
  },
  underLine: {
    height: 1.5,
    marginTop: 14,
    alignSelf: 'center',
    backgroundColor: HEX_COLOR_CODES.MID_GRAY,
    width: LAYOUT_CONSTRAINTS.SCREEN_WIDTH - 26,
  },
  switchContainer: {
    flex: 0.9,
  },
  shareMyIdIcon: {
    position: 'relative',
    marginLeft: 24,
    height: 20,
    width: 22,
    bottom: 2,
  },
  trackColorWhenFalse: {
    color: HEX_COLOR_CODES.TRACK_FALSE,
  },
  trackColorWhenTrue: {
    color: HEX_COLOR_CODES.TRACK_TRUE,
  },
  switchStyle: {
    position: 'absolute',
    right: 3,
    top: 12,
  },
  thumbColorWhenEnabled: {
    color: HEX_COLOR_CODES.THUMB_ENABLED,
  },
  thumbColorWhenDisEnabled: {
    color: HEX_COLOR_CODES.THUMB_DISABLED,
  },
  profileInfoIconContainer: {
    position: 'absolute',
    right: 3,
    top: 12,
    height: 35,
    width: 37,
    borderRadius: 4,
    alignItems: 'center',
    justifyContent: 'center',
  },
  crossIconContainer: {
    position: 'absolute',
    right: 3,
    top: 4,
    height: 35,
    width: 37,
    borderRadius: 4,
    backgroundColor: HEX_COLOR_CODES.BLACK,
    alignItems: 'center',
    justifyContent: 'center',
  },
  profileInfoButton: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
  },
  profileInfoIcon: {
    position: 'relative',
    right: 12,
    height: 24,
    width: 24,
  },
  unverifiedProfileInfoIconBackGround: {
    backgroundColor: HEX_COLOR_CODES.ORANGE,
  },
  infoIconTextStyle: {
    height: 0,
    width: 0,
  },
  infoAlertcontainer: {
    position: 'absolute',
    height: 115,
    width: LAYOUT_CONSTRAINTS.WINDOW_WIDTH - 28,
    marginLeft: 14,
    backgroundColor: HEX_COLOR_CODES.BLACK,
    zIndex: 1,
    marginTop: 60,
    borderRadius: 4,
  },
  infoLabel: {
    fontSize: 14,
    fontFamily: FONTS.SOFIA_REGULAR,
    color: HEX_COLOR_CODES.WHITE,
    paddingLeft: 14,
    paddingTop: 32,
    marginRight: 88,
  },
  infoLabelColor: {
    color: HEX_COLOR_CODES.WHITE,
  },
  anitibodyLabel: {
    color: HEX_COLOR_CODES.GREEN,
    textDecorationLine: 'underline',
  },
  errorStyle: {
    height: '100%',
    backgroundColor: HEX_COLOR_CODES.GREY_BG,
    width: '100%',
  },
});
