export const EDIT_TEST_FIELDS_ACTION = 'EDIT_TEST_FIELDS_ACTION';
export const SUBMIT_TEST_DATA_ACTION = 'SUBMIT_TEST_DATA_ACTION';
export const TEST_DATA_API_FAILURE = 'TEST_DATA_API_FAILURE';
export const TEST_DATA_API_SUCCESS = 'TEST_DATA_API_SUCCESS';
export const ADD_TEST_FIELDS_ACTION = 'ADD_TEST_FIELDS_ACTION';
export const SAVE_TEST_DETAIL_FROM_API_ACTION =
  'SAVE_TEST_DETAIL_FROM_API_ACTION';
export const UPDATE_TEST_FIELD_TYPE_AND_INDEX_ACTION =
  'UPDATE_TEST_FIELD_TYPE_AND_INDEX_ACTION';
export const CHECK_MISSING_FIELDS_ACTION = 'CHECK_MISSING_FIELDS_ACTION';
export const DELETE_TEST_DETAIL_ROW_ACTION = 'DELETE_TEST_DETAIL_ROW_ACTION';
export const CHECK_MISSING_FIELDS_IN_TESTOBJECT_ACTION =
  'CHECK_MISSING_FIELDS_IN_TESTOBJECT_ACTION';
export const UPLOAD_HEALTH_TEST_IMAGE_ACTION =
  'UPLOAD_HEALTH_TEST_IMAGE_ACTION';
export const UPLOAD_HEALTH_TEST_IMAGE_FAILURE_ACTION =
  'UPLOAD_HEALTH_TEST_IMAGE_FAILURE_ACTION';
export const EDIT_HEALTH_TEST_DATA_AFTER_IMAGE_UPLOAD_ACTION =
  'EDIT_HEALTH_TEST_DATA_AFTER_IMAGE_UPLOAD_ACTION';
export const UPDATE_MISSING_FIELD_ACTION = 'UPDATE_MISSING_FIELD_ACTION';
export const UPDATE_TEST_ACTION = 'UPDATE_TEST_ACTION';
export const UPDATE_TEST_SUCCESS = 'UPDATE_TEST_SUCCESS';
export const UPDATE_TEST_FAILURE = 'UPDATE_TEST_FAILURE';
