export const BECOME_MEDICAL_APPROVER = 'BECOME_MEDICAL_APPROVER_ACTION';
export const BECOME_MEDICAL_APPROVER_SUCCESS_ACTION =
  'BECOME_MEDICAL_APPROVER_SUCCESS_ACTION';
export const BECOME_MEDICAL_APPROVER_FAILURE_ACTION =
  'BECOME_MEDICAL_APPROVER_FAILURE_ACTION';
