export const EDIT_PERSONALDETAILS_ACTION = 'EDIT_PERSONALDETAILS_ACTION';
export const EDIT_FIRSTNAME_ACTION = 'EDIT_FIRSTNAME_ACTION';
export const EDIT_LASTNAME_ACTION = 'EDIT_LASTNAME_ACTION';
export const EDIT_MIDDLENAME_ACTION = 'EDIT_MIDDLENAME_ACTION';
export const ADD_PERSONAL_DETAILS_ACTION = 'ADD_PERSONAL_DETAILS_ACTION';
export const PERSONAL_DETAILS_SUCCESS_ACTION =
  'PERSONAL_DETAILS_SUCCESS_ACTION';
export const PERSONAL_DETAILS_FAILURE_ACTION =
  'PERSONAL_DETAILS_FAILURE_ACTION';
export const MISSING_FILEDS_ACTION = 'MISSING_FILEDS_ACTION';
export const PERSONAL_DETAILS_ACCESS_TOKEN_ACTION =
  'PERSONAL_DETAILS_ACCESS_TOKEN_ACTION';
export const SIGNUP_STEP_ACTION = 'SIGNUP_STEP_ACTION';
export const STORE_USERID_ACTION = 'STORE_USERID_ACTION';
