export const EDIT_CONTACT_DETAILS_ACTION = 'EDIT_CONTACT_DETAILS_ACTION';
export const POLICY_SERVICE_CHECKED_ACTION = 'POLICY_SERVICE_CHECKED_ACTION';
export const ADD_CONTACT_DETAILS_ACTION = 'ADD_CONTACT_DETAILS_ACTION';
export const CONTACT_DETAILS_SUCCESS_ACTION = 'CONTACT_DETAILS_SUCCESS_ACTION';
export const CONTACT_DETAILS_FAILURE_ACTION = 'CONTACT_DETAILS_FAILURE_ACTION';
export const MISSING_CONTACT_FILEDS_ACTION = 'MISSING_CONTACT_FILEDS_ACTION';
export const GET_COUNTRY_LIST_ACTION = 'GET_COUNTRY_LIST_ACTION';
export const GOT_COUNTRY_LIST_SUCCESS_ACTION =
  'GOT_COUNTRY_LIST_SUCCESS_ACTION';
export const GOT_COUNTRY_LIST_FAILURE_ACTION =
  'GOT_COUNTRY_LIST_FAILURE_ACTION';
