export const DO_SIGN_IN_ACTION = 'DO_SIGN_IN_ACTION';
export const SIGN_IN_SUCCESS_ACTION = 'SIGN_IN_SUCCESS_ACTION';
export const SIGN_IN_FAILURE_ACTION = 'SIGN_IN_FAILURE_ACTION';
export const STORE_TOKEN_ACTION = 'STORE_TOKEN_ACTION';
export const REMOVE_TOKEN_ACTION = 'REMOVE_TOKEN_ACTION';
export const STORE_DEVICE_TOKEN_ACTION = 'STORE_DEVICE_TOKEN_ACTION';
export const TOKEN_STORED_ACTION = 'TOKEN_ACTION';
export const STORE_UDERID_ACTION = 'STORE_UDERID_ACTION';
