export const GET_TEMPERATURE_HISTORY = 'GET_TEMPERATURE_HISTORY';
export const GET_TEMPERATURE_HISTORY_SUCCESS =
  'GET_TEMPERATURE_HISTORY_SUCCESS';
export const GET_TEMPERATURE_HISTORY_FAILURE =
  'GET_TEMPERATURE_HISTORY_FAILURE';
export const UPDATE_TEMPERATURE_HISTORY_MODAL_INDEX_ACTION =
  'UPDATE_TEMPERATURE_HISTORY_MODAL_INDEX_ACTION';
