export const SEND_PUBLIC_KEY = 'SEND_PUBLIC_KEY';
export const PUBLIC_KEY_CREATED = 'PUBLIC_KEY_CREATED';
export const PUBLIC_KEY_CREATE_FAIL = 'PUBLIC_KEY_CREATE_FAIL';
export const BIOMETRIC_SIGN_ACTION = 'BIOMETRIC_SIGN_ACTION';
export const UPDATE_PUBLIC_KEY = 'UPDATE_PUBLIC_KEY';
