export const CHECKIN_LIST_ACTION = 'CHECKIN_LIST_ACTION';
export const CHECKIN_LIST_SUCCESS_ACTION = 'CHECKIN_LIST_SUCCESS_ACTION';
export const CHECKIN_LIST_FAILURE_ACTION = 'CHECKIN_LIST_FAILURE_ACTION';
export const MANUAL_CHECKOUT = 'MANUAL_CHECKOUT';
export const MANUAL_CHECKOUT_SUCCESS = 'MANUAL_CHECKOUT_SUCCESS';
export const MANUAL_CHECKOUT_FAILURE = 'MANUAL_CHECKOUT_FAILURE';
