import {API_BASE_URL, JUMIO_CALLBACK_URL} from '../../config';

export const URLS = {
  API_BASE_URL,
  JUMIO_CALLBACK_URL,
  TESTED_ME_WEBSITE: 'https://www.tested.me',
  TESTED_ME_DYNAMIC_LINK_DOMAIN: 'https://testedme.page.link',
  TESTED_ME_BUSINESS: 'https://tested.me/for-business',
  TESTED_ME_SUPPORT: 'https://support.tested.me',

  SIGNUP_URL: 'signup',
  SIGNOUT_URL: 'signout',
  LOGIN_URL: 'signin',
  FORGOT_PASSWORD_URL: 'forgot-password',
  CONTACT_DETAILS_URL: 'users',
  CODE_LIST_URL: 'phone-code',
  VERIFY_OTP_URL: 'verify-sms',
  RESEND_OTP_URL: 'resend-sms',
  HEALTH_STAT_URL: 'stats',
  HEALTH_TEST_URL: 'health-tests',
  CREATE_DEEPLINKING_URL: 'create-link',
  ME_SIGN_DETAILS: 'users/me-details',
  GET_JUMIO_CREDENTIALS: 'api-details',
  UPDATE_TEMP_URL: 'temperature-details',
  HEALTH_DETAILS: 'health-details',
  GET_OTHER_USER_DETAILS_VIA_DYNAMIC_LINK: 'users-details',
  GET_OTHER_USER_DETAILS_VIA_ME: 'users/me-details',
  GET_OTHER_USER_NAME_VIA_ME: 'users/basic-details',
  PRE_SIGNED: 'presigned-details',
  NOTIFICATIONS_URL: 'notifications',
  PRIVACY_POLICY_URL: 'https://app.tested.me/privacy-policy',
  TC_URL: 'https://app.tested.me/eula',
  UPDATE_CONTACT_DETAILS_URL: '/profiles',
  VERIFY_OTP_FOR_USER_DETAILS: 'verify',
  CHANGE_PASSWORD_URL: '/password',
  TEMPERATURE_HISTORY_URL: 'temperature-details',
  BUSINESS_EMPLOYEE_INVITATION: 'invitations',
  GET_COMPANY_BY_QR_CODE: 'company-by-qr',
  ACCEPT_SHARING_CONTACT_DETAILS: 'visitor-by-mobile',
  HEALTH_TEST_RESULTS: 'health-details',
  ENABLE_BIOMETRIC: 'enable-biometric',
  BIOMETRIC_SIGN: 'signin-via-biometric',
  CONTACT_DETAILS_ON_SETTINGS: '/contact-details',
  UPDATE: '/update',
  UPDATE_HEALTH_TEST: 'health_tests',
  REMOVE_EMPLOYER: 'remove-employer',
  FORCE_UPDATE: 'force-updates',
  OPERATING_SYSTEM: 'operating_system',
  VERSION: 'version',
  SHARE_HISTORY: 'share-history',
  TOGGLE_REMOTE_WORK: 'users/working_remotely',
  GET_COMPANIES: 'companies',
  DEFAULT_COMPANY: 'default',
  WORKING_REMOTELY: '/working-remotely',
  DELETE_ACCOUNT_URL: 'self',
  REMOTE_WORKING_REASONS: 'employees/remote-working-reasons',
  VISITORS: 'visitors',
  CHECKOUT: 'visitors/check-out',
  CHECKIN_LIST: '/checked-in-list',
  VACCINATION: 'vaccinations',
  DEVICE_TOKEN: '/device-token',
  REVIEW_HEALTH_TEST: 'review-health-tests',
  VERIFY_VACCINE_DETAILS: 'vaccination-details',
  REVIEW_VACCINE: 'review-vaccinations',
  MEDICAL_APPROVER: 'approver-details',
  TOKEN: 'token',
  VACCINE_TYPES: 'vaccination-types',
  VACCINATION_WITH_TYPE: 'vaccinations-with-type',
};
