export const GET_VACCINATIONS_ACTION = 'GET_VACCINATIONS_ACTION';
export const VACCINATIONS_SUCCESS_ACTION = 'VACCINATIONS_SUCCESS_ACTION';
export const VACCINATIONS_FAIL_ACTION = 'VACCINATIONS_FAIL_ACTION';
export const DELETE_VACCINE_ACTION = 'DELETE_VACCINE_ACTION';
export const DELETE_VACCINE_SUCCESS_ACTION = 'DELETE_VACCINE_SUCCESS_ACTION';
export const DELETE_VACCINE_FAIL_ACTION = 'DELETE_VACCINE_FAIL_ACTION';
export const UPLOAD_VACCINE_IMAGE = 'UPLOAD_VACCINE_IMAGE';
export const UPLOAD_VACCINE_DETAILS = 'UPLOAD_VACCINE_DETAILS';
export const UPLOAD_VACCINE_DETAILS_SUCCESS = 'UPLOAD_VACCINE_DETAILS_SUCCESS';
export const UPLOAD_VACCINE_DETAILS_FAILURE = 'UPLOAD_VACCINE_DETAILS_FAILURE';
export const UPLOAD_VACCINE_IMAGE_FAILURE = 'UPLOAD_VACCINE_IMAGE_SUCCESS';
export const UPLOAD_VACCINE_IMAGE_SUCCESS = 'UPLOAD_VACCINE_IMAGE_SUCCESS';
export const RESET_VACCINE_DETAILS = 'RESET_VACCINE_DETAILS';
export const EDIT_VACCINE_DETAILS = 'EDIT_VACCINE_DETAILS';
export const EDIT_VACCINE_DETAILS_SUCCESS = 'EDIT_VACCINE_DETAILS_SUCCESS';
export const EDIT_VACCINE_DETAILS_FAILURE = 'EDIT_VACCINE_DETAILS_FAILURE';
export const SHOW_VACCINE_MODAL_ACTION = 'SHOW_VACCINE_MODAL_ACTION';
export const SET_VACCINE_FIELDS_TO_BE_EDITED =
  'SET_VACCINE_FIELDS_TO_BE_EDITED';
export const SET_VACCINE_NAME_ACTION = 'SET_VACCINE_NAME_ACTION';
export const SET_VACCINE_CENTRE_ACTION = 'SET_VACCINE_CENTRE_ACTION';
export const SET_VACCINE_ADD_DATE_ACTION = 'SET_VACCINE_ADD_DATE_ACTION';
export const SET_VACCINE_EXPIRE_DATE_ACTION = 'SET_VACCINE_EXPIRE_DATE_ACTION';
export const SET_VACCINE_DOCUMENT_ACTION = 'SET_VACCINE_DOCUMENT_ACTION';
export const GET_VACCINE_DETAILS_ACTION = 'GET_VACCINE_DETAILS_ACTION';
export const GET_VACCINE_DETAILS_SUCCESS_ACTION =
  'GET_VACCINE_DETAILS_SUCCESS_ACTION';
export const GET_VACCINE_DETAILS_FAILURE_ACTION =
  'GET_VACCINE_DETAILS_FAILURE_ACTION';
export const REVIEW_VACCINE_ACTION = 'REVIEW_VACCINE_ACTION';
export const REVIEW_VACCINE_SUCCESS_ACTION =
  'GET_VACCINE_DETAILS_SUCCESS_ACTION';
export const REVIEW_VACCINE_FAILURE_ACTION =
  'GET_VACCINE_DETAILS_FAILURE_ACTION';
export const GET_VACCINE_TYPES_ACTION = 'GET_VACCINE_TYPES_ACTION';
export const SET_VACCINE_TYPES_SUCCESS_ACTION =
  'SET_VACCINE_TYPES_SUCCESS_ACTION';
export const GET_VACCINE_TYPES_FAILURE_ACTION =
  'GET_VACCINE_TYPES_FAILURE_ACTION';
